### ISSUE TITLE
[ui] 가게 상세화면 UI

### ISSUE THREAD

**Issue by NaZe0320** [UMC-5th-Kumo/Coumo_AOS#10]
## 🛠️ ISSUE

- 가게 상세화면 UI 개발

## 📑 To-Do

- [ ] Drawer 구현
- [ ] 탭 구현
- [ ] 매장 정보 Fragment
   - [ ] 메뉴 아이템 구현
   - [ ] 지도 미리보기 구현
- [ ] 내 쿠폰 보기 Fragment (UI 만)
