### ISSUE TITLE
[ui] 내 계정 페이지 디자인 변경 사항 구현 

### ISSUE THREAD

**Issue by NaZe0320** [UMC-5th-Kumo/Coumo_AOS#18]
## 🛠️ ISSUE

- 내 계정 디자인 변경사항 수정
- 프로필 부분 닉네임 삭제
- 탈퇴하기 기능 구현

## 📑 To-Do

- [ ] 프로필 닉네임 삭제
- [ ] 탈퇴하기 버튼 추가
- [ ] 탈퇴하기 Dialog 추가
