### ISSUE TITLE
[style] font weight 미적용된 부분 적용

### ISSUE THREAD

**Issue by NaZe0320** [UMC-5th-Kumo/Coumo_AOS#21]
## 🛠️ ISSUE

- 폰트 스타일 적용 (weight 미적용 text 적용)

## 📑 To-Do

- [x] 동네 소식 Font Weight 적용
- [x] Item/Chip Font Weight 적용
- [x] 내 계정 Font Weight 적용
- [x] Bottom Navi Font Weight 적용
- [x] 내 쿠폰 Font Weight 적용
