### ISSUE TITLE
[ui] 홈 화면 구현

### ISSUE THREAD

**Issue by NaZe0320** [UMC-5th-Kumo/Coumo_AOS#32]
## 🛠️ ISSUE

- 광고 ViewPager 구현
- 아이콘 삽입
- 인기 매장 리스트 구현

## 📑 To-Do
- [ ] 광고 ViewPager 구현
- [ ] 메뉴 아이콘 삽입
- [ ] 인기 매장 리스트 구현
