### ISSUE TITLE
[feat] 메인 홈 페이지 연결 및 기능 구현

### ISSUE THREAD

**Issue by NaZe0320** [UMC-5th-Kumo/Coumo_AOS#34]
## 🛠️ ISSUE

- 리스트 -> 상세 정보 화면 아이템 별 연결
- 인기 매장 -> 상세 정보 화면 연결
- 쿠폰 -> 상세 정보 화면 (쿠폰 탭) 연결
- 아이템 Model 연결

## 📑 To-Do

- [x] item <-> Model 연결
   - [x] 가게 리스트
   - [x] 메뉴 아이콘/메뉴 리스트
   - [x] 가게 정보
- [ ] 화면 연결
   - [x] 가게 리스트 -> 상세 정보 화면
   - [x] 인기 매장 -> 상세 정보 화면 (Back Track 홈 화면)
   - [ ] 내 쿠폰(쿠폰 클릭) -> 해당 가게 상세 정보 화면 (쿠폰 탭)
