### ISSUE TITLE
[feat] 홈화면 API 연결 1차

### ISSUE THREAD

**Issue by NaZe0320** [UMC-5th-Kumo/Coumo_AOS#38]
## 🛠️ ISSUE

- 인기 매장 api 연결
- 근처 매장 api 연결
- 가게 상세화면 api 연결

## 📑 To-Do

- [x] API 초기 세팅
- [x] 인기 매장 API 연결
- [x] 근처 매장 API 연결
- [ ] 가게 상세화면 API 연결
- [x] customerId sharedPreference 구현
- [x] 로그인 테스트 (요청 사항)
