### ISSUE TITLE
[feat] 가게 상세정보 API 연결

### ISSUE THREAD

**Issue by NaZe0320** [UMC-5th-Kumo/Coumo_AOS#45]
## 🛠️ ISSUE

- 인기 매장 api 연결
- 근처 매장 api 연결
- 가게 상세화면 api 연결

## 📑 To-Do

- [x] 가게 상세정보 Response/Request Model 구현
- [x] 가게 상세 정보 API 구현
- [x] 가게 상세 정보 페이지 UI 수정사항 반영
