### ISSUE TITLE
[feat] 사장님 UI 구현 및 기능 구현

### ISSUE THREAD

**Issue by NaZe0320** [UMC-5th-Kumo/Coumo_AOS#48]
## 🛠️ ISSUE

- QR 연결 화면 구현
- 설정(프로필 및 로그아웃 화면 구현)

## 📑 To-Do

- [x] 설정화면 (가게 프로필, 전화, 로그아웃)
- [x] QR 화면 구현
- [ ] 적립/사용 선택 화면
   - [ ] 적립 시, 개수 선택 Dialog
   - [x] 사용 화면 UI
