### ISSUE TITLE
[feat] 쿠폰 상세화면 구현

### ISSUE THREAD

**Issue by NaZe0320** [UMC-5th-Kumo/Coumo_AOS#51]
## 🛠️ ISSUE

- 쿠폰 적립 위한 화면 구현

## 📑 To-Do

- [x] 쿠폰 상세 화면 구현(Dialog)
- [ ] 쿠폰 아이템 구현
   - [x] 쿠폰 QR 플립 구현
   - [ ] 쿠폰 데이터 모델 구현
- [ ] 적립/사용 선택 화면
