### ISSUE TITLE
[feat] 가게 정보 아이템 Adapter 및 Model 생성

### ISSUE THREAD

**Issue by NaZe0320** [UMC-5th-Kumo/Coumo_AOS#6]
## 🛠️ ISSUE

- 가게 정보 아이템 Adapter 및 Model 개발

## 📑 To-Do

- [x] item_store_info Model 개발
- [x] item_store_info DataBinding
- [x] item_store_info Adatper 개발
