### ISSUE TITLE
[feat] Store Coupon Adapter 및 Model 생성

### ISSUE THREAD

**Issue by NaZe0320** [UMC-5th-Kumo/Coumo_AOS#7]
## 🛠️ ISSUE

- Store Coupon Item Adapter 및 Model 개발

## 📑 To-Do

- [x] item_store_coupon_count Model 개발
- [x] item_store_coupon_count DataBinding
- [x] item_store_coupon_count Adatper 개발
